FROM node:13.12.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./ 
RUN npm install --silent
RUN npm install react-scripts@4.0.3 -g --silent
COPY . ./

# nay chay duoi dev, khong phai tren prod :((
CMD ["npm", "start"]
EXPOSE 3000