name: CI - Backend
on:
  pull_request:
    branches:
      - main  
jobs:
  ci-backend:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u vidao1233 -p d@oVi1233
      - name: Build Frontend
        run: docker build -t vidao1233/toeic-web:v1 .
      - name: Push image
        run: docker push vidao1233/toeic-web:v1