name: CI - Frontend
on:
  pull_request:
    paths:
      - "**/*"
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u tranngobichdu -p du2392002
      - name: Build Frontend
        run: docker build -t tranngobichdu/toeic-learning-website:v1 .
      - name: Push image
        run: docker push tranngobichdu/toeic-learning-website:v1