name: github ci/cd

env:
  DOTNET_VERSION: "6.0" # set this to the .NET Core version to use
  WORKING_DIRECTORY: "./src" #define the root folder path

on:
  push:
    branches:
      - main

jobs:
  build-and-push-be:
    name: Build and Push Docker Image BE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup test loggers
        shell: pwsh
        run: |
          foreach ($file in Get-ChildItem -Path .src/tests/*Tests.csproj -Recurse)
          {
            dotnet add $file package JunitXml.TestLogger --source 'https://api.nuget.org/v3/index.json'
          }

      - name: Run unit tests
        shell: bash
        working-directory: ./src
        run: |
          dotnet test toiec-web.sln --logger 'junit;LogFileName=TestResults.xml' \
            --verbosity normal --results-directory ./_test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ./src/_test-results/*.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build BE Docker Image
        run: docker build -t vidao1233/toeic-web:v1 -f .build/be/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_BE }}
          password: ${{ secrets.DOCKER_PASSWORD_BE }}

      - name: Push Docker Image
        run: docker push vidao1233/toeic-web:v1

  build-and-push-fe:
    name: Build and Push Docker Image FE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build FE Docker Image
        run: docker build -t tranngobichdu/toeic-learning-website:v1 -f .build/fe/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_FE }}
          password: ${{ secrets.DOCKER_PASSWORD_FE }}

      - name: Push Docker Image
        run: docker push tranngobichdu/toeic-learning-website:v1

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-be, build-and-push-fe]
    steps:
      - name: SSH into the server and deploy Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 103.130.211.150
          username: ${{ secrets.DOCKER_USERNAME_HOST }}
          password: ${{ secrets.DOCKER_PASSWORD_HOST }}
          port: 10038
          script: |
            cd ~/project/20110223_20110618/toeicweb/learning-toeic
            chmod +x .build/sqlserver/entrypoint.sh
            chmod +x .build/sqlserver/run-initialization.sh
            git pull origin main
            docker compose -f docker-compose.yml down -v
            docker compose -f docker-compose.yml up --build -d
